server:
  servlet:
    context-path: /
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reservation?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 1
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1
    timeout: 100000
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false


mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.justin.reservationsystem.model




