-- ----------------------------
-- TABLE STRUCTURE FOR WF_GEN_TABLE
-- ----------------------------

CREATE TABLE WF_GEN_TABLE (
	ID NVARCHAR2 (64) NOT NULL,
	PROCESS_DESIGN_ID NVARCHAR2 (64) NULL,
	PROCESS_DEF_ID NVARCHAR2 (64) NULL,
	TASK_DEF_ID NVARCHAR2 (64) NULL,
	NAME NVARCHAR2 (200) NULL,
	COMMENTS NVARCHAR2 (500) NULL,
	CLASS_NAME NVARCHAR2 (100) NULL,
	STYLE_TYPE NCHAR (1) NULL,
	PARENT_TABLE NVARCHAR2 (200) NULL,
	PARENT_TABLE_FK NVARCHAR2 (100) NULL,
	CREATE_BY NVARCHAR2 (64) NULL,
	CREATE_DATE DATE NULL,
	UPDATE_BY NVARCHAR2 (64) NULL,
	UPDATE_DATE DATE NULL,
	REMARKS NVARCHAR2 (255) NULL,
	DEL_FLAG NCHAR (1) NOT NULL
);

COMMENT ON TABLE WF_GEN_TABLE IS '业务表';

COMMENT ON COLUMN WF_GEN_TABLE. ID IS '编号';

COMMENT ON COLUMN WF_GEN_TABLE.PROCESS_DESIGN_ID IS '流程方案ID';

COMMENT ON COLUMN WF_GEN_TABLE.TASK_DEF_ID IS '任务ID';

COMMENT ON COLUMN WF_GEN_TABLE. NAME IS '名称';

COMMENT ON COLUMN WF_GEN_TABLE.COMMENTS IS '描述';

COMMENT ON COLUMN WF_GEN_TABLE.CLASS_NAME IS '实体类名称';

COMMENT ON COLUMN WF_GEN_TABLE.STYLE_TYPE IS '表单样式(1:单列；0：双列)';

COMMENT ON COLUMN WF_GEN_TABLE.PARENT_TABLE IS '关联父表';

COMMENT ON COLUMN WF_GEN_TABLE.PARENT_TABLE_FK IS '关联父表外键';

COMMENT ON COLUMN WF_GEN_TABLE.CREATE_BY IS '创建者';

COMMENT ON COLUMN WF_GEN_TABLE.CREATE_DATE IS '创建时间';

COMMENT ON COLUMN WF_GEN_TABLE.UPDATE_BY IS '更新者';

COMMENT ON COLUMN WF_GEN_TABLE.UPDATE_DATE IS '更新时间';

COMMENT ON COLUMN WF_GEN_TABLE.REMARKS IS '备注信息';

COMMENT ON COLUMN WF_GEN_TABLE.DEL_FLAG IS '删除标记（0：正常；1：删除）';

ALTER TABLE WF_GEN_TABLE ADD PRIMARY KEY (ID);

CREATE INDEX WF_GEN_TABLE_DEL_FLAG ON WF_GEN_TABLE (DEL_FLAG ASC);

CREATE INDEX WF_GEN_TABLE_NAME ON WF_GEN_TABLE (NAME ASC);

ALTER TABLE WF_GEN_TABLE ADD CHECK (ID IS NOT NULL);

ALTER TABLE WF_GEN_TABLE ADD CHECK (DEL_FLAG IS NOT NULL);

-- ----------------------------
-- TABLE STRUCTURE FOR WF_GEN_TABLE_COLUMN
-- ----------------------------

CREATE TABLE WF_GEN_TABLE_COLUMN (
	ID NVARCHAR2 (64) NOT NULL,
	WF_GEN_TABLE_ID NVARCHAR2 (64) NULL,
	NAME NVARCHAR2 (200) NULL,
	COMMENTS NVARCHAR2 (500) NULL,
	JDBC_TYPE NVARCHAR2 (100) NULL,
	JAVA_TYPE NVARCHAR2 (500) NULL,
	JAVA_FIELD NVARCHAR2 (200) NULL,
	IS_PK NCHAR (1) NULL,
	IS_NULL NCHAR (1) NULL,
	IS_INSERT NCHAR (1) NULL,
	IS_EDIT NCHAR (1) NULL,
	IS_LIST NCHAR (1) NULL,
	IS_QUERY NCHAR (1) NULL,
	QUERY_TYPE NVARCHAR2 (200) NULL,
	SHOW_TYPE NVARCHAR2 (200) NULL,
	DICT_TYPE NVARCHAR2 (200) NULL,
	SETTINGS NCLOB NULL,
	SORT NUMBER NULL,
	CREATE_BY NVARCHAR2 (64) NULL,
	CREATE_DATE DATE NULL,
	UPDATE_BY NVARCHAR2 (64) NULL,
	UPDATE_DATE DATE NULL,
	REMARKS NVARCHAR2 (255) NULL,
	DEL_FLAG NCHAR (1) NOT NULL
);

COMMENT ON TABLE WF_GEN_TABLE_COLUMN IS '业务表字段';

COMMENT ON COLUMN WF_GEN_TABLE_COLUMN. ID IS '编号';

COMMENT ON COLUMN WF_GEN_TABLE_COLUMN.WF_GEN_TABLE_ID IS '归属表编号';

COMMENT ON COLUMN WF_GEN_TABLE_COLUMN. NAME IS '名称';

COMMENT ON COLUMN WF_GEN_TABLE_COLUMN.COMMENTS IS '描述';

COMMENT ON COLUMN WF_GEN_TABLE_COLUMN.JDBC_TYPE IS '列的数据类型的字节长度';

COMMENT ON COLUMN WF_GEN_TABLE_COLUMN.JAVA_TYPE IS 'JAVA类型';

COMMENT ON COLUMN WF_GEN_TABLE_COLUMN.JAVA_FIELD IS 'JAVA字段名';

COMMENT ON COLUMN WF_GEN_TABLE_COLUMN.IS_PK IS '是否主键';

COMMENT ON COLUMN WF_GEN_TABLE_COLUMN.IS_NULL IS '是否可为空';

COMMENT ON COLUMN WF_GEN_TABLE_COLUMN.IS_INSERT IS '是否为插入字段';

COMMENT ON COLUMN WF_GEN_TABLE_COLUMN.IS_EDIT IS '是否编辑字段';

COMMENT ON COLUMN WF_GEN_TABLE_COLUMN.IS_LIST IS '是否列表字段';

COMMENT ON COLUMN WF_GEN_TABLE_COLUMN.IS_QUERY IS '是否查询字段';

COMMENT ON COLUMN WF_GEN_TABLE_COLUMN.QUERY_TYPE IS '查询方式（等于、不等于、大于、小于、范围、左LIKE、右LIKE、左右LIKE）';

COMMENT ON COLUMN WF_GEN_TABLE_COLUMN.SHOW_TYPE IS '字段生成方案（文本框、文本域、下拉框、复选框、单选框、字典选择、人员选择、部门选择、区域选择）';

COMMENT ON COLUMN WF_GEN_TABLE_COLUMN.DICT_TYPE IS '字典类型';

COMMENT ON COLUMN WF_GEN_TABLE_COLUMN. SETTINGS IS '其它设置（扩展字段JSON）';

COMMENT ON COLUMN WF_GEN_TABLE_COLUMN. SORT IS '排序（升序）';

COMMENT ON COLUMN WF_GEN_TABLE_COLUMN.CREATE_BY IS '创建者';

COMMENT ON COLUMN WF_GEN_TABLE_COLUMN.CREATE_DATE IS '创建时间';

COMMENT ON COLUMN WF_GEN_TABLE_COLUMN.UPDATE_BY IS '更新者';

COMMENT ON COLUMN WF_GEN_TABLE_COLUMN.UPDATE_DATE IS '更新时间';

COMMENT ON COLUMN WF_GEN_TABLE_COLUMN.REMARKS IS '备注信息';

COMMENT ON COLUMN WF_GEN_TABLE_COLUMN.DEL_FLAG IS '删除标记（0：正常；1：删除）';


CREATE INDEX WF_GEN_TABLE_COLUMN_DEL_FLAG ON WF_GEN_TABLE_COLUMN (DEL_FLAG ASC);

CREATE INDEX WF_GEN_TABLE_COLUMN_NAME ON WF_GEN_TABLE_COLUMN (NAME ASC);

CREATE INDEX WF_GEN_TABLE_COLUMN_SORT ON WF_GEN_TABLE_COLUMN (SORT ASC);

CREATE INDEX WF_GEN_TABLE_COLUMN_TABLE_ID ON WF_GEN_TABLE_COLUMN (WF_GEN_TABLE_ID ASC);

ALTER TABLE WF_GEN_TABLE_COLUMN ADD CHECK (ID IS NOT NULL);

ALTER TABLE WF_GEN_TABLE_COLUMN ADD CHECK (DEL_FLAG IS NOT NULL);

ALTER TABLE WF_GEN_TABLE_COLUMN ADD PRIMARY KEY (ID);

-- ----------------------------
-- TABLE STRUCTURE FOR WF_HI_DELEGATE
-- ----------------------------

CREATE TABLE WF_HI_DELEGATE (
	ID NVARCHAR2 (36) NOT NULL,
	ASSIGNEE NVARCHAR2 (200) NULL,
	ATTORNEY NVARCHAR2 (200) NULL,
	DELEGATE_TIME DATE NOT NULL,
	TASK_ID NVARCHAR2 (100) NULL,
	STATUS NUMBER (11) NOT NULL
) ;

COMMENT ON TABLE WF_HI_DELEGATE IS '历史代理信息表';

COMMENT ON COLUMN WF_HI_DELEGATE. ID IS 'ID';

COMMENT ON COLUMN WF_HI_DELEGATE.ASSIGNEE IS '办理人';

COMMENT ON COLUMN WF_HI_DELEGATE.ATTORNEY IS '代理人';

COMMENT ON COLUMN WF_HI_DELEGATE.DELEGATE_TIME IS '设置代理信息时间';

COMMENT ON COLUMN WF_HI_DELEGATE.TASK_ID IS '任务ID';

COMMENT ON COLUMN WF_HI_DELEGATE.STATUS IS '状态';

ALTER TABLE WF_HI_DELEGATE ADD CHECK (ID IS NOT NULL);

ALTER TABLE WF_HI_DELEGATE ADD CHECK (DELEGATE_TIME IS NOT NULL);

ALTER TABLE WF_HI_DELEGATE ADD CHECK (STATUS IS NOT NULL);

ALTER TABLE WF_HI_DELEGATE ADD PRIMARY KEY (ID);


-- ----------------------------
-- TABLE STRUCTURE FOR WF_HI_TASK_EXPAND_DATA
-- ----------------------------

CREATE TABLE WF_HI_TASK_EXPAND_DATA (
	ID NVARCHAR2 (64) NOT NULL,
	TASK_EXPAND_PLAN_ID NVARCHAR2 (64) NOT NULL,
	PROCESS_INST_ID NVARCHAR2 (64) NOT NULL,
	PROCESS_DEF_ID NVARCHAR2 (64) NOT NULL,
	TASK_ID NVARCHAR2 (64) NOT NULL,
	TASK_NODE_ID NVARCHAR2 (64) NOT NULL,
	FIELD01 NVARCHAR2 (256) NULL,
	FIELD02 NVARCHAR2 (256) NULL,
	FIELD03 NVARCHAR2 (256) NULL,
	FIELD04 NVARCHAR2 (256) NULL,
	FIELD05 NVARCHAR2 (256) NULL,
	FIELD06 NVARCHAR2 (256) NULL,
	FIELD07 NVARCHAR2 (256) NULL,
	FIELD08 NVARCHAR2 (256) NULL,
	FIELD09 NVARCHAR2 (256) NULL,
	FIELD10 NVARCHAR2 (256) NULL,
	FIELD11 NVARCHAR2 (256) NULL,
	FIELD12 NVARCHAR2 (256) NULL,
	FIELD13 NVARCHAR2 (256) NULL,
	FIELD14 NVARCHAR2 (256) NULL,
	FIELD15 NVARCHAR2 (256) NULL,
	FIELD16 NVARCHAR2 (256) NULL,
	FIELD17 NVARCHAR2 (256) NULL,
	FIELD18 NVARCHAR2 (256) NULL,
	FIELD19 NVARCHAR2 (256) NULL,
	FIELD20 NVARCHAR2 (256) NULL
) ;

COMMENT ON TABLE WF_HI_TASK_EXPAND_DATA IS '待办扩展历史数据表';

COMMENT ON COLUMN WF_HI_TASK_EXPAND_DATA. ID IS 'ID';

COMMENT ON COLUMN WF_HI_TASK_EXPAND_DATA.TASK_EXPAND_PLAN_ID IS '代办拓展方案ID';

COMMENT ON COLUMN WF_HI_TASK_EXPAND_DATA.PROCESS_INST_ID IS '流程实例ID';

COMMENT ON COLUMN WF_HI_TASK_EXPAND_DATA.PROCESS_DEF_ID IS '流程定义ID';

COMMENT ON COLUMN WF_HI_TASK_EXPAND_DATA.TASK_ID IS '待办任务ID';

COMMENT ON COLUMN WF_HI_TASK_EXPAND_DATA.TASK_NODE_ID IS '待办任务节点ID';

COMMENT ON COLUMN WF_HI_TASK_EXPAND_DATA.FIELD01 IS '拓展字段01';

COMMENT ON COLUMN WF_HI_TASK_EXPAND_DATA.FIELD02 IS '拓展字段02';

COMMENT ON COLUMN WF_HI_TASK_EXPAND_DATA.FIELD03 IS '拓展字段03';

COMMENT ON COLUMN WF_HI_TASK_EXPAND_DATA.FIELD04 IS '拓展字段04';

COMMENT ON COLUMN WF_HI_TASK_EXPAND_DATA.FIELD05 IS '拓展字段05';

COMMENT ON COLUMN WF_HI_TASK_EXPAND_DATA.FIELD06 IS '拓展字段06';

COMMENT ON COLUMN WF_HI_TASK_EXPAND_DATA.FIELD07 IS '拓展字段07';

COMMENT ON COLUMN WF_HI_TASK_EXPAND_DATA.FIELD08 IS '拓展字段08';

COMMENT ON COLUMN WF_HI_TASK_EXPAND_DATA.FIELD09 IS '拓展字段09';

COMMENT ON COLUMN WF_HI_TASK_EXPAND_DATA.FIELD10 IS '拓展字段10';

COMMENT ON COLUMN WF_HI_TASK_EXPAND_DATA.FIELD11 IS '拓展字段11';

COMMENT ON COLUMN WF_HI_TASK_EXPAND_DATA.FIELD12 IS '拓展字段12';

COMMENT ON COLUMN WF_HI_TASK_EXPAND_DATA.FIELD13 IS '拓展字段13';

COMMENT ON COLUMN WF_HI_TASK_EXPAND_DATA.FIELD14 IS '拓展字段14';

COMMENT ON COLUMN WF_HI_TASK_EXPAND_DATA.FIELD15 IS '拓展字段15';

COMMENT ON COLUMN WF_HI_TASK_EXPAND_DATA.FIELD16 IS '拓展字段16';

COMMENT ON COLUMN WF_HI_TASK_EXPAND_DATA.FIELD17 IS '拓展字段17';

COMMENT ON COLUMN WF_HI_TASK_EXPAND_DATA.FIELD18 IS '拓展字段18';

COMMENT ON COLUMN WF_HI_TASK_EXPAND_DATA.FIELD19 IS '拓展字段19';

COMMENT ON COLUMN WF_HI_TASK_EXPAND_DATA.FIELD20 IS '拓展字段20';


ALTER TABLE WF_HI_TASK_EXPAND_DATA ADD CHECK (ID IS NOT NULL);

ALTER TABLE WF_HI_TASK_EXPAND_DATA ADD CHECK (
	TASK_EXPAND_PLAN_ID IS NOT NULL
);

ALTER TABLE WF_HI_TASK_EXPAND_DATA ADD CHECK (PROCESS_INST_ID IS NOT NULL);

ALTER TABLE WF_HI_TASK_EXPAND_DATA ADD CHECK (PROCESS_DEF_ID IS NOT NULL);

ALTER TABLE WF_HI_TASK_EXPAND_DATA ADD CHECK (TASK_ID IS NOT NULL);

ALTER TABLE WF_HI_TASK_EXPAND_DATA ADD CHECK (TASK_NODE_ID IS NOT NULL);

ALTER TABLE WF_HI_TASK_EXPAND_DATA ADD PRIMARY KEY (ID);

-- ----------------------------
-- TABLE STRUCTURE FOR WF_PROCESS_CLASSIFY
-- ----------------------------

CREATE TABLE WF_PROCESS_CLASSIFY (
	ID NVARCHAR2 (64) NOT NULL,
	PARENT_ID NVARCHAR2 (64) NOT NULL,
	PARENT_IDS NCLOB NOT NULL,
	NAME NVARCHAR2 (100) NOT NULL,
	SORT NUMBER NOT NULL,
	CODE NVARCHAR2 (100) NOT NULL,
	TYPE NCHAR (1) NOT NULL,
	USEABLE NVARCHAR2 (64) NOT NULL,
	CREATE_BY NVARCHAR2 (64) NOT NULL,
	CREATE_DATE DATE NOT NULL,
	UPDATE_BY NVARCHAR2 (64) NOT NULL,
	UPDATE_DATE DATE NOT NULL,
	REMARKS NVARCHAR2 (255) NULL,
	DEL_FLAG NCHAR (1) NOT NULL
) ;

COMMENT ON TABLE WF_PROCESS_CLASSIFY IS '流程分类表';

COMMENT ON COLUMN WF_PROCESS_CLASSIFY. ID IS '编号';

COMMENT ON COLUMN WF_PROCESS_CLASSIFY.PARENT_ID IS '父级编号';

COMMENT ON COLUMN WF_PROCESS_CLASSIFY.PARENT_IDS IS '所有父级编号';

COMMENT ON COLUMN WF_PROCESS_CLASSIFY. NAME IS '名称';

COMMENT ON COLUMN WF_PROCESS_CLASSIFY. SORT IS '排序';

COMMENT ON COLUMN WF_PROCESS_CLASSIFY.CODE IS '分类编号';

COMMENT ON COLUMN WF_PROCESS_CLASSIFY. TYPE IS '分类类型';

COMMENT ON COLUMN WF_PROCESS_CLASSIFY.USEABLE IS '是否启用';

COMMENT ON COLUMN WF_PROCESS_CLASSIFY.CREATE_BY IS '创建者';

COMMENT ON COLUMN WF_PROCESS_CLASSIFY.CREATE_DATE IS '创建时间';

COMMENT ON COLUMN WF_PROCESS_CLASSIFY.UPDATE_BY IS '更新者';

COMMENT ON COLUMN WF_PROCESS_CLASSIFY.UPDATE_DATE IS '更新时间';

COMMENT ON COLUMN WF_PROCESS_CLASSIFY.REMARKS IS '备注信息';

COMMENT ON COLUMN WF_PROCESS_CLASSIFY.DEL_FLAG IS '删除标记';

CREATE INDEX WF_PROCESS_DEL_FLAG ON WF_PROCESS_CLASSIFY (DEL_FLAG ASC);

CREATE INDEX WF_PROCESS_PARENT_ID ON WF_PROCESS_CLASSIFY (PARENT_ID ASC);

CREATE INDEX WF_PROCESS_TYPE ON WF_PROCESS_CLASSIFY (TYPE ASC);

ALTER TABLE WF_PROCESS_CLASSIFY ADD CHECK (ID IS NOT NULL);

ALTER TABLE WF_PROCESS_CLASSIFY ADD CHECK (PARENT_ID IS NOT NULL);

ALTER TABLE WF_PROCESS_CLASSIFY ADD CHECK (PARENT_IDS IS NOT NULL);

ALTER TABLE WF_PROCESS_CLASSIFY ADD CHECK (NAME IS NOT NULL);

ALTER TABLE WF_PROCESS_CLASSIFY ADD CHECK (SORT IS NOT NULL);

ALTER TABLE WF_PROCESS_CLASSIFY ADD CHECK (CODE IS NOT NULL);

ALTER TABLE WF_PROCESS_CLASSIFY ADD CHECK (TYPE IS NOT NULL);

ALTER TABLE WF_PROCESS_CLASSIFY ADD CHECK (USEABLE IS NOT NULL);

ALTER TABLE WF_PROCESS_CLASSIFY ADD CHECK (CREATE_BY IS NOT NULL);

ALTER TABLE WF_PROCESS_CLASSIFY ADD CHECK (CREATE_DATE IS NOT NULL);

ALTER TABLE WF_PROCESS_CLASSIFY ADD CHECK (UPDATE_BY IS NOT NULL);

ALTER TABLE WF_PROCESS_CLASSIFY ADD CHECK (UPDATE_DATE IS NOT NULL);

ALTER TABLE WF_PROCESS_CLASSIFY ADD CHECK (DEL_FLAG IS NOT NULL);

ALTER TABLE WF_PROCESS_CLASSIFY ADD PRIMARY KEY (ID);


-- ----------------------------
-- TABLE STRUCTURE FOR WF_PROCESS_CONFIG
-- ----------------------------

CREATE TABLE WF_PROCESS_CONFIG (
	ID NVARCHAR2 (64) NOT NULL,
	PROC_DEF_ID NVARCHAR2 (64) NOT NULL,
	ACT_ID NVARCHAR2 (64) NULL,
	ACT_NAME NVARCHAR2 (64) NULL,
	PROCESS_STARTED_CLASS NVARCHAR2 (255) NULL,
	PROCESS_COMPLETED_CLASS NVARCHAR2 (255) NULL,
	BAS_RECEIVE_CLASS NVARCHAR2 (255) NULL,
	BAS_INVOKE_TYPE NVARCHAR2 (255) NULL,
	BAS_DISPOSE_TYPE NVARCHAR2 (255) NULL,
	PAR_PARTICIPANT_MODE NVARCHAR2 (255) NULL,
	PAR_NODE NVARCHAR2 (255) NULL,
	PAR_ROLE NVARCHAR2 (255) NULL,
	PAR_PERSONNL NVARCHAR2 (255) NULL,
	PAR_RULE_PROJECT NVARCHAR2 (255) NULL,
	PAR_RULE_CODE NVARCHAR2 (255) NULL,
	TIME_TYPE NVARCHAR2 (255) NULL,
	TIME_CALULATION NVARCHAR2 (255) NULL,
	TIME_RELATIVE NVARCHAR2 (255) NULL,
	TIME_DISPOSE_TYPE NVARCHAR2 (255) NULL,
	TIME_REMIND_TIME NVARCHAR2 (255) NULL,
	TIME_REMIND_FREQUENCY NVARCHAR2 (255) NULL,
	TIME_REMIND_NUM NVARCHAR2 (255) NULL,
	TIME_REMIND_TYPE NVARCHAR2 (255) NULL,
	TIME_REMIND_TEXT NCLOB NULL,
	USER_TASK_ASSIGNMENT NVARCHAR2 (1000) NULL,
	NODE_FUNCTION NVARCHAR2 (1000) NULL,
	PROCESS_STATUS NVARCHAR2 (8) NULL
) ;

COMMENT ON TABLE WF_PROCESS_CONFIG IS '流程配置表';

COMMENT ON COLUMN WF_PROCESS_CONFIG. ID IS 'ID';

COMMENT ON COLUMN WF_PROCESS_CONFIG.PROC_DEF_ID IS '流程定义ID';

COMMENT ON COLUMN WF_PROCESS_CONFIG.ACT_ID IS '节点ID';

COMMENT ON COLUMN WF_PROCESS_CONFIG.ACT_NAME IS '节点名称';

COMMENT ON COLUMN WF_PROCESS_CONFIG.PROCESS_STARTED_CLASS IS '流程启动处理类';

COMMENT ON COLUMN WF_PROCESS_CONFIG.PROCESS_COMPLETED_CLASS IS '流程结束处理类';

COMMENT ON COLUMN WF_PROCESS_CONFIG.BAS_RECEIVE_CLASS IS '业务处理类';

COMMENT ON COLUMN WF_PROCESS_CONFIG.BAS_INVOKE_TYPE IS '调用方式';

COMMENT ON COLUMN WF_PROCESS_CONFIG.BAS_DISPOSE_TYPE IS '处理方式';

COMMENT ON COLUMN WF_PROCESS_CONFIG.PAR_PARTICIPANT_MODE IS '参与者模式';

COMMENT ON COLUMN WF_PROCESS_CONFIG.PAR_NODE IS '节点';

COMMENT ON COLUMN WF_PROCESS_CONFIG.PAR_ROLE IS '角色';

COMMENT ON COLUMN WF_PROCESS_CONFIG.PAR_PERSONNL IS '人员';

COMMENT ON COLUMN WF_PROCESS_CONFIG.PAR_RULE_PROJECT IS '规则项目';

COMMENT ON COLUMN WF_PROCESS_CONFIG.PAR_RULE_CODE IS '规则编码';

COMMENT ON COLUMN WF_PROCESS_CONFIG.TIME_TYPE IS '时间类型';

COMMENT ON COLUMN WF_PROCESS_CONFIG.TIME_CALULATION IS '时间计算策略';

COMMENT ON COLUMN WF_PROCESS_CONFIG.TIME_RELATIVE IS '相对时间';

COMMENT ON COLUMN WF_PROCESS_CONFIG.TIME_DISPOSE_TYPE IS '处理方式';

COMMENT ON COLUMN WF_PROCESS_CONFIG.TIME_REMIND_TIME IS '提醒时间';

COMMENT ON COLUMN WF_PROCESS_CONFIG.TIME_REMIND_FREQUENCY IS '提醒频率';

COMMENT ON COLUMN WF_PROCESS_CONFIG.TIME_REMIND_NUM IS '提醒次数';

COMMENT ON COLUMN WF_PROCESS_CONFIG.TIME_REMIND_TYPE IS '提醒方式';

COMMENT ON COLUMN WF_PROCESS_CONFIG.TIME_REMIND_TEXT IS '提醒内容模板设置';

COMMENT ON COLUMN WF_PROCESS_CONFIG.USER_TASK_ASSIGNMENT IS '处理人配置';

COMMENT ON COLUMN WF_PROCESS_CONFIG.NODE_FUNCTION IS '节点功能';

COMMENT ON COLUMN WF_PROCESS_CONFIG.PROCESS_STATUS IS '任务或流程状态1或0';

ALTER TABLE WF_PROCESS_CONFIG ADD CHECK (ID IS NOT NULL);

ALTER TABLE WF_PROCESS_CONFIG ADD CHECK (PROC_DEF_ID IS NOT NULL);

-- ----------------------------
-- PRIMARY KEY STRUCTURE FOR TABLE WF_PROCESS_CONFIG
-- ----------------------------
ALTER TABLE WF_PROCESS_CONFIG ADD PRIMARY KEY (ID);


-- ----------------------------
-- TABLE STRUCTURE FOR WF_PROCESS_DESIGN
-- ----------------------------

CREATE TABLE WF_PROCESS_DESIGN (
	ID NVARCHAR2 (64) NOT NULL,
	DESIGN_NAME NVARCHAR2 (255) NOT NULL,
	DESIGN_KEY NVARCHAR2 (255) NOT NULL,
	DESIGN_STATUS NCHAR (1) NOT NULL,
	DESIGN_DESCRIPTION NCLOB NULL,
	PROCESS_DEF_ID NVARCHAR2 (64) NULL
) ;

COMMENT ON COLUMN WF_PROCESS_DESIGN. ID IS 'ID';

COMMENT ON COLUMN WF_PROCESS_DESIGN.DESIGN_NAME IS '方案名称';

COMMENT ON COLUMN WF_PROCESS_DESIGN.DESIGN_KEY IS '方案KEY';

COMMENT ON COLUMN WF_PROCESS_DESIGN.DESIGN_STATUS IS '状态';

COMMENT ON COLUMN WF_PROCESS_DESIGN.DESIGN_DESCRIPTION IS '方案描述';

COMMENT ON COLUMN WF_PROCESS_DESIGN.PROCESS_DEF_ID IS '流程定义ID';

ALTER TABLE WF_PROCESS_DESIGN ADD CHECK (ID IS NOT NULL);

ALTER TABLE WF_PROCESS_DESIGN ADD CHECK (DESIGN_NAME IS NOT NULL);

ALTER TABLE WF_PROCESS_DESIGN ADD CHECK (DESIGN_KEY IS NOT NULL);

ALTER TABLE WF_PROCESS_DESIGN ADD CHECK (DESIGN_STATUS IS NOT NULL);

ALTER TABLE WF_PROCESS_DESIGN ADD PRIMARY KEY (ID);


-- ----------------------------
-- TABLE STRUCTURE FOR WF_PROCESS_VARIABLE
-- ----------------------------

CREATE TABLE WF_PROCESS_VARIABLE (
	ID NVARCHAR2 (36) NOT NULL,
	TASK_DEF_ID NVARCHAR2 (64) NULL,
	VARIABLE_KEY NVARCHAR2 (64) NULL,
	VARIABLE_VAL NVARCHAR2 (64) NULL,
	VARIABLE_NAME NVARCHAR2 (32) NULL,
	TASK_DEF_NAME NVARCHAR2 (64) NULL,
	PROCESS_DEF_ID NVARCHAR2 (255) NULL,
	PROCESS_DESIGN_ID NVARCHAR2 (255) NULL
) ;

COMMENT ON TABLE WF_PROCESS_VARIABLE IS '变量配置';

COMMENT ON COLUMN WF_PROCESS_VARIABLE. ID IS 'ID';

COMMENT ON COLUMN WF_PROCESS_VARIABLE.TASK_DEF_ID IS '任务定义ID';

COMMENT ON COLUMN WF_PROCESS_VARIABLE.VARIABLE_KEY IS '变量标识';

COMMENT ON COLUMN WF_PROCESS_VARIABLE.VARIABLE_VAL IS '变量值';

COMMENT ON COLUMN WF_PROCESS_VARIABLE.VARIABLE_NAME IS '变量名称';

COMMENT ON COLUMN WF_PROCESS_VARIABLE.TASK_DEF_NAME IS '任务定义名称';

COMMENT ON COLUMN WF_PROCESS_VARIABLE.PROCESS_DEF_ID IS '任务定义ID';

COMMENT ON COLUMN WF_PROCESS_VARIABLE.PROCESS_DESIGN_ID IS '流程设计方案ID';

ALTER TABLE WF_PROCESS_VARIABLE ADD CHECK (ID IS NOT NULL);

ALTER TABLE WF_PROCESS_VARIABLE ADD PRIMARY KEY (ID);


-- ----------------------------
-- TABLE STRUCTURE FOR WF_RU_DELEGATE
-- ----------------------------

CREATE TABLE WF_RU_DELEGATE (
	ID NVARCHAR2 (36) NOT NULL,
	ASSIGNEE NVARCHAR2 (200) NULL,
	ATTORNEY NVARCHAR2 (200) NULL,
	START_TIME DATE NULL,
	END_TIME DATE NULL,
	PROCESS_DEFINITION_ID NVARCHAR2 (100) NULL,
	STATUS NUMBER (11) NULL,
	PROCESS_DEFINITION_NAME NVARCHAR2 (100) NULL
) ;

COMMENT ON TABLE WF_RU_DELEGATE IS '代理信息表';

COMMENT ON COLUMN WF_RU_DELEGATE. ID IS 'ID';

COMMENT ON COLUMN WF_RU_DELEGATE.ASSIGNEE IS '办理人';

COMMENT ON COLUMN WF_RU_DELEGATE.ATTORNEY IS '代理人';

COMMENT ON COLUMN WF_RU_DELEGATE.START_TIME IS '起始时间';

COMMENT ON COLUMN WF_RU_DELEGATE.END_TIME IS '结束时间';

COMMENT ON COLUMN WF_RU_DELEGATE.PROCESS_DEFINITION_ID IS '流程定义ID';

COMMENT ON COLUMN WF_RU_DELEGATE.STATUS IS '状态';

COMMENT ON COLUMN WF_RU_DELEGATE.PROCESS_DEFINITION_NAME IS '流程定义名称';

ALTER TABLE WF_RU_DELEGATE ADD CHECK (ID IS NOT NULL);

ALTER TABLE WF_RU_DELEGATE ADD PRIMARY KEY (ID);

-- ----------------------------
-- TABLE STRUCTURE FOR WF_TASK_EXPAND_DATA
-- ----------------------------

CREATE TABLE WF_TASK_EXPAND_DATA (
	ID NVARCHAR2 (64) NOT NULL,
	TASK_EXPAND_PLAN_ID NVARCHAR2 (64) NOT NULL,
	PROCESS_INST_ID NVARCHAR2 (64) NOT NULL,
	PROCESS_DEF_ID NVARCHAR2 (64) NOT NULL,
	TASK_ID NVARCHAR2 (64) NOT NULL,
	TASK_NODE_ID NVARCHAR2 (64) NOT NULL,
	FIELD01 NVARCHAR2 (256) NULL,
	FIELD02 NVARCHAR2 (256) NULL,
	FIELD03 NVARCHAR2 (256) NULL,
	FIELD04 NVARCHAR2 (256) NULL,
	FIELD05 NVARCHAR2 (256) NULL,
	FIELD06 NVARCHAR2 (256) NULL,
	FIELD07 NVARCHAR2 (256) NULL,
	FIELD08 NVARCHAR2 (256) NULL,
	FIELD09 NVARCHAR2 (256) NULL,
	FIELD10 NVARCHAR2 (256) NULL,
	FIELD11 NVARCHAR2 (256) NULL,
	FIELD12 NVARCHAR2 (256) NULL,
	FIELD13 NVARCHAR2 (256) NULL,
	FIELD14 NVARCHAR2 (256) NULL,
	FIELD15 NVARCHAR2 (256) NULL,
	FIELD16 NVARCHAR2 (256) NULL,
	FIELD17 NVARCHAR2 (256) NULL,
	FIELD18 NVARCHAR2 (256) NULL,
	FIELD19 NVARCHAR2 (256) NULL,
	FIELD20 NVARCHAR2 (256) NULL
) ;

COMMENT ON TABLE WF_TASK_EXPAND_DATA IS '流程待办扩展运行数据表';

COMMENT ON COLUMN WF_TASK_EXPAND_DATA. ID IS 'ID';

COMMENT ON COLUMN WF_TASK_EXPAND_DATA.TASK_EXPAND_PLAN_ID IS '代办拓展方案ID';

COMMENT ON COLUMN WF_TASK_EXPAND_DATA.PROCESS_INST_ID IS '流程实例ID';

COMMENT ON COLUMN WF_TASK_EXPAND_DATA.PROCESS_DEF_ID IS '流程定义ID';

COMMENT ON COLUMN WF_TASK_EXPAND_DATA.TASK_ID IS '待办任务ID';

COMMENT ON COLUMN WF_TASK_EXPAND_DATA.TASK_NODE_ID IS '待办任务节点ID';

COMMENT ON COLUMN WF_TASK_EXPAND_DATA.FIELD01 IS '拓展字段01';

COMMENT ON COLUMN WF_TASK_EXPAND_DATA.FIELD02 IS '拓展字段02';

COMMENT ON COLUMN WF_TASK_EXPAND_DATA.FIELD03 IS '拓展字段03';

COMMENT ON COLUMN WF_TASK_EXPAND_DATA.FIELD04 IS '拓展字段04';

COMMENT ON COLUMN WF_TASK_EXPAND_DATA.FIELD05 IS '拓展字段05';

COMMENT ON COLUMN WF_TASK_EXPAND_DATA.FIELD06 IS '拓展字段06';

COMMENT ON COLUMN WF_TASK_EXPAND_DATA.FIELD07 IS '拓展字段07';

COMMENT ON COLUMN WF_TASK_EXPAND_DATA.FIELD08 IS '拓展字段08';

COMMENT ON COLUMN WF_TASK_EXPAND_DATA.FIELD09 IS '拓展字段09';

COMMENT ON COLUMN WF_TASK_EXPAND_DATA.FIELD10 IS '拓展字段10';

COMMENT ON COLUMN WF_TASK_EXPAND_DATA.FIELD11 IS '拓展字段11';

COMMENT ON COLUMN WF_TASK_EXPAND_DATA.FIELD12 IS '拓展字段12';

COMMENT ON COLUMN WF_TASK_EXPAND_DATA.FIELD13 IS '拓展字段13';

COMMENT ON COLUMN WF_TASK_EXPAND_DATA.FIELD14 IS '拓展字段14';

COMMENT ON COLUMN WF_TASK_EXPAND_DATA.FIELD15 IS '拓展字段15';

COMMENT ON COLUMN WF_TASK_EXPAND_DATA.FIELD16 IS '拓展字段16';

COMMENT ON COLUMN WF_TASK_EXPAND_DATA.FIELD17 IS '拓展字段17';

COMMENT ON COLUMN WF_TASK_EXPAND_DATA.FIELD18 IS '拓展字段18';

COMMENT ON COLUMN WF_TASK_EXPAND_DATA.FIELD19 IS '拓展字段19';

COMMENT ON COLUMN WF_TASK_EXPAND_DATA.FIELD20 IS '拓展字段20';

ALTER TABLE WF_TASK_EXPAND_DATA ADD CHECK (ID IS NOT NULL);

ALTER TABLE WF_TASK_EXPAND_DATA ADD CHECK (
	TASK_EXPAND_PLAN_ID IS NOT NULL
);

ALTER TABLE WF_TASK_EXPAND_DATA ADD CHECK (PROCESS_INST_ID IS NOT NULL);

ALTER TABLE WF_TASK_EXPAND_DATA ADD CHECK (PROCESS_DEF_ID IS NOT NULL);

ALTER TABLE WF_TASK_EXPAND_DATA ADD CHECK (TASK_ID IS NOT NULL);

ALTER TABLE WF_TASK_EXPAND_DATA ADD CHECK (TASK_NODE_ID IS NOT NULL);

ALTER TABLE WF_TASK_EXPAND_DATA ADD PRIMARY KEY (ID);
-- ----------------------------
-- TABLE STRUCTURE FOR WF_TASK_EXPAND_PLAN
-- ----------------------------

CREATE TABLE WF_TASK_EXPAND_PLAN (
	ID NVARCHAR2 (64) NOT NULL,
	WF_CLASS_ID NVARCHAR2 (64) NOT NULL,
	WF_CLASS_NAME NVARCHAR2 (256) NOT NULL,
	FIELD_KEY NVARCHAR2 (64) NULL,
	FIELD_NAME NVARCHAR2 (256) NULL,
	FIELD_VALUE NVARCHAR2 (256) NULL,
	FIELD_TYPE NVARCHAR2 (256) NULL,
	FIELD_URL NVARCHAR2 (256) NULL,
	FIELD_STATUS NVARCHAR2 (16) NULL
) ;

COMMENT ON COLUMN WF_TASK_EXPAND_PLAN. ID IS 'ID';

COMMENT ON COLUMN WF_TASK_EXPAND_PLAN.WF_CLASS_ID IS '流程分类ID';

COMMENT ON COLUMN WF_TASK_EXPAND_PLAN.WF_CLASS_NAME IS '流程分类名称';

COMMENT ON COLUMN WF_TASK_EXPAND_PLAN.FIELD_KEY IS '拓展字段键值';

COMMENT ON COLUMN WF_TASK_EXPAND_PLAN.FIELD_NAME IS '拓展字段名称';

COMMENT ON COLUMN WF_TASK_EXPAND_PLAN.FIELD_VALUE IS '拓展字段数值';

COMMENT ON COLUMN WF_TASK_EXPAND_PLAN.FIELD_TYPE IS '类型';

COMMENT ON COLUMN WF_TASK_EXPAND_PLAN.FIELD_URL IS '链接';

COMMENT ON COLUMN WF_TASK_EXPAND_PLAN.FIELD_STATUS IS '是否隐藏';

ALTER TABLE WF_TASK_EXPAND_PLAN ADD CHECK (ID IS NOT NULL);

ALTER TABLE WF_TASK_EXPAND_PLAN ADD CHECK (WF_CLASS_ID IS NOT NULL);

ALTER TABLE WF_TASK_EXPAND_PLAN ADD CHECK (WF_CLASS_NAME IS NOT NULL);

ALTER TABLE WF_TASK_EXPAND_PLAN ADD PRIMARY KEY (ID);
-- ----------------------------
-- TABLE STRUCTURE FOR WF_TENANT
-- ----------------------------

CREATE TABLE WF_TENANT (
	ID NVARCHAR2 (64) NOT NULL,
	TENANT_ID NVARCHAR2 (256) NULL,
	NAME NVARCHAR2 (256) NULL,
	CREATE_BY NVARCHAR2 (256) NULL,
	CREATE_DATE DATE NULL,
	UPDATE_BY NVARCHAR2 (64) NULL,
	UPDATE_DATE DATE NULL,
	REMARKS NVARCHAR2 (256) NULL,
	DEL_FLAG NCHAR (1) NOT NULL
) ;

COMMENT ON TABLE WF_TENANT IS '租户表';

COMMENT ON COLUMN WF_TENANT. ID IS '主键';

COMMENT ON COLUMN WF_TENANT.TENANT_ID IS '租户标识';

COMMENT ON COLUMN WF_TENANT. NAME IS '租户名称';

COMMENT ON COLUMN WF_TENANT.CREATE_BY IS '创建者';

COMMENT ON COLUMN WF_TENANT.CREATE_DATE IS '创建时间';

COMMENT ON COLUMN WF_TENANT.UPDATE_BY IS '更新者';

COMMENT ON COLUMN WF_TENANT.UPDATE_DATE IS '更新时间';

COMMENT ON COLUMN WF_TENANT.REMARKS IS '备注信息';

COMMENT ON COLUMN WF_TENANT.DEL_FLAG IS '删除标记（0：正常；1：删除）';

ALTER TABLE WF_TENANT ADD CHECK (ID IS NOT NULL);

ALTER TABLE WF_TENANT ADD CHECK (DEL_FLAG IS NOT NULL);

ALTER TABLE WF_TENANT ADD PRIMARY KEY (ID);
-- ----------------------------
-- TABLE STRUCTURE FOR WF_VIEW_CONFIG
-- ----------------------------

CREATE TABLE WF_VIEW_CONFIG (
	ID NVARCHAR2 (36) NOT NULL,
	PROCESS_DEF_ID NVARCHAR2 (64)  NULL,
	TASK_DEF_ID NVARCHAR2 (64)  NULL,
	BIZ_DETAIL_NAME NVARCHAR2 (100) NULL,
	BIZ_DETAIL_URL NVARCHAR2 (200) NULL,
	BIZ_DETAIL_PARAM NVARCHAR2 (200) NULL,
	BIZ_OPERATION NCLOB NULL,
	PROCESS_DESIGN_ID NVARCHAR2 (64) NULL
) ;

COMMENT ON COLUMN WF_VIEW_CONFIG. ID IS 'ID';

COMMENT ON COLUMN WF_VIEW_CONFIG.PROCESS_DEF_ID IS '流程定义ID';

COMMENT ON COLUMN WF_VIEW_CONFIG.TASK_DEF_ID IS '任务定义ID';

COMMENT ON COLUMN WF_VIEW_CONFIG.BIZ_DETAIL_NAME IS '业务信息页面名称';

COMMENT ON COLUMN WF_VIEW_CONFIG.BIZ_DETAIL_URL IS '业务信息页面地址';

COMMENT ON COLUMN WF_VIEW_CONFIG.BIZ_DETAIL_PARAM IS '业务信息页面参数';

COMMENT ON COLUMN WF_VIEW_CONFIG.BIZ_OPERATION IS '操作权限控制';

COMMENT ON COLUMN WF_VIEW_CONFIG.PROCESS_DESIGN_ID IS '流程方案ID';


ALTER TABLE WF_VIEW_CONFIG ADD PRIMARY KEY (ID);
-- ----------------------------
-- TABLE STRUCTURE FOR WF_VIEW_RELATED_LINKS
-- ----------------------------

CREATE TABLE WF_VIEW_RELATED_LINKS (
	ID NVARCHAR2 (36) NOT NULL,
	PROCESS_DEF_ID NVARCHAR2 (64) NULL,
	TASK_DEF_ID NVARCHAR2 (64) NOT NULL,
	LINK_NAME NVARCHAR2 (100) NULL,
	LINK_URL NVARCHAR2 (200) NULL,
	LINK_PARAM NVARCHAR2 (200) NULL,
	SORT_NO NUMBER NULL
) ;

COMMENT ON COLUMN WF_VIEW_RELATED_LINKS. ID IS 'ID';

COMMENT ON COLUMN WF_VIEW_RELATED_LINKS.PROCESS_DEF_ID IS '流程定义ID';

COMMENT ON COLUMN WF_VIEW_RELATED_LINKS.TASK_DEF_ID IS '任务定义编号';

COMMENT ON COLUMN WF_VIEW_RELATED_LINKS.LINK_NAME IS '链接名称';

COMMENT ON COLUMN WF_VIEW_RELATED_LINKS.LINK_URL IS '链接地址';

COMMENT ON COLUMN WF_VIEW_RELATED_LINKS.LINK_PARAM IS '链接参数';

COMMENT ON COLUMN WF_VIEW_RELATED_LINKS.SORT_NO IS '排序';

ALTER TABLE WF_VIEW_RELATED_LINKS ADD CHECK (ID IS NOT NULL);

ALTER TABLE WF_VIEW_RELATED_LINKS ADD CHECK (TASK_DEF_ID IS NOT NULL);

ALTER TABLE WF_VIEW_RELATED_LINKS ADD PRIMARY KEY (ID);

ALTER TABLE WF_PROCESS_DESIGN
MODIFY ( "DESIGN_NAME" NVARCHAR2(255) NULL  )
MODIFY ( "DESIGN_KEY" NVARCHAR2(255) NULL  )
MODIFY ( "DESIGN_STATUS" NCHAR(1) NULL  ) ;


ALTER TABLE  WF_VIEW_CONFIG
MODIFY ( "PROCESS_DEF_ID" NVARCHAR2(64) NULL  )
MODIFY ( "TASK_DEF_ID" NVARCHAR2(64) NULL  ) ;

CREATE TABLE WF_DEFINED_BUTTON (
  ID NVARCHAR2(36) NOT NULL,
  KEY NVARCHAR2(200) NULL,
  NAME NVARCHAR2(200) NULL,
  ALIAS NVARCHAR2(200) NULL,
  STATUS NVARCHAR2(8) NULL
);
COMMENT ON TABLE WF_DEFINED_BUTTON IS '按钮自定义设置表';

COMMENT ON COLUMN WF_DEFINED_BUTTON. ID IS 'ID';

COMMENT ON COLUMN WF_DEFINED_BUTTON. KEY IS '按钮key';

COMMENT ON COLUMN WF_DEFINED_BUTTON. NAME IS '按钮名称';

COMMENT ON COLUMN WF_DEFINED_BUTTON. ALIAS IS '按钮别名';

COMMENT ON COLUMN WF_DEFINED_BUTTON. STATUS IS '状态1失效0生效';

ALTER TABLE WF_DEFINED_BUTTON ADD PRIMARY KEY (ID);

INSERT INTO WF_DEFINED_BUTTON VALUES ('0a86e8a3526d4223afd3d8e3102c910c', 'nextTask', '下一步', '下一步', '1');
INSERT INTO WF_DEFINED_BUTTON VALUES ('3f11484ccb5141bd84c304bcb4bf419b', 'processMsg', '查看流程过程信息', '查看流程过程信息', '1');
INSERT INTO WF_DEFINED_BUTTON VALUES ('444ec5ae0d0a4f9681c9e6049483fe03', 'terminateProcess', '终止流程', '终止流程', '1');
INSERT INTO WF_DEFINED_BUTTON VALUES ('4d13d7b836c547a4975cc5bf0438f259', 'lastTask', '回退至上一步', '回退至上一步', '1');
INSERT INTO WF_DEFINED_BUTTON VALUES ('7290ac3e2842491e849a217cf395d816', 'suspendProcess', '挂起流程', '挂起流程', '1');
INSERT INTO WF_DEFINED_BUTTON VALUES ('7caa66e5afa2431fb4da0ab5c57093f3', 'addGroupUser', '加签', '加签', '1');
INSERT INTO WF_DEFINED_BUTTON VALUES ('afab98ffc20d474db2809bf12531c4b4', 'getTask', '获取任务', '获取任务', '1');
INSERT INTO WF_DEFINED_BUTTON VALUES ('b3634ec91f2245428220ae79116ab98b', 'activateProcess', '激活流程', '激活流程', '1');
INSERT INTO WF_DEFINED_BUTTON VALUES ('cbc443de2bf5494fb7e432ec5a2b869e', 'relay', '转发', '转发', '1');
INSERT INTO WF_DEFINED_BUTTON VALUES ('cce811bab4974e93bfd83a53e8695ea7', 'releaseTask', '释放任务', '释放任务', '1');
INSERT INTO WF_DEFINED_BUTTON VALUES ('eb6ca12f5002470094f1e798914c5df0', 'delGroupUser', '减签', '减签', '1');
INSERT INTO WF_DEFINED_BUTTON VALUES ('f660c65a1ca44763a633e46bcb246356', 'firstTask', '退回第一步', '退回第一步', '1');
INSERT INTO WF_DEFINED_BUTTON VALUES ('fc0c5d20771147d7beab59717dba3e8e', 'getBack', '取回', '取回', '3');
INSERT INTO WF_DEFINED_BUTTON VALUES ('fc7ba9635f1948468ef0175c63d71dad', 'appointTask', '退回指定节点', '退回指定节点', '1');


CREATE TABLE wf_timer_config (
	id varchar2(36) NOT NULL,
  proc_def_id varchar2(64),
	task_def_key varchar2(255),
	proc_inst_id varchar2(64),
	execution_id varchar2(64),
	cron_expression varchar2(255),
  time_type varchar2(64),
	begin_time TIMESTAMP(6),
	end_time TIMESTAMP(6),
	cfrequency NUMBER(20),
  remind_num NUMBER(20),
	send_type varchar2(64),
	create_time TIMESTAMP(6),
	note varchar2(2000),
	status varchar2(8),
  template varchar2(1000),
  tenant_id varchar2(256)
);

COMMENT ON COLUMN wf_timer_config.id IS '定时配置信息ID';
COMMENT ON COLUMN wf_timer_config.proc_def_id IS '流程定义ID';
COMMENT ON COLUMN wf_timer_config.task_def_key IS '任务节点ID';
COMMENT ON COLUMN wf_timer_config.proc_inst_id IS '流程实例ID';
COMMENT ON COLUMN wf_timer_config.execution_id IS '执行实例ID';
COMMENT ON COLUMN wf_timer_config.cron_expression IS 'cron时间表达式';
COMMENT ON COLUMN wf_timer_config.time_type IS '时间类型：工作日,自然日';
COMMENT ON COLUMN wf_timer_config.begin_time IS '提醒相对时间';
COMMENT ON COLUMN wf_timer_config.end_time IS '结束相对时间';
COMMENT ON COLUMN wf_timer_config.cfrequency IS '提醒频率,单位秒';
COMMENT ON COLUMN wf_timer_config.remind_num IS '提醒次数';
COMMENT ON COLUMN wf_timer_config.send_type IS '提醒方式：email邮件shortMessage短信withinMessage';
COMMENT ON COLUMN wf_timer_config.create_time IS '创建时间';
COMMENT ON COLUMN wf_timer_config.note IS '定时任务备注';
COMMENT ON COLUMN wf_timer_config.status IS '状态0正常1失效';
COMMENT ON COLUMN wf_timer_config.template IS '消息模板';
COMMENT ON COLUMN wf_timer_config.tenant_id IS '租户标识';

COMMIT ;




